package pt.isec.pa.apoio_poe.model.fsm;

public enum ReturnValue {
    ALREADY_CLOSED, NO_STUDENTS, CLOSED_SUCESSFULLY,
    INSF_PROPS_RAS_STUDENTS, INSF_PROPS_SI_STUDENTS, INSF_PROPS_DA_STUDENTS,
    NULL, PREVIOUS_PHASE_NOT_CLOSED, STUDENT_WITHOUT_PROPS,
}
